package com.example.nomadly;

import android.os.Bundle;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

public class ExpenseActivity extends AppCompatActivity {

    private EditText purposeInput, whoSpentInput, amountInput;
    private Button saveButton, cancelButton;
    private ExpenseDatabaseHelper dbHelper;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_expense);

        // Initialize UI components
        purposeInput = findViewById(R.id.purpose_input);
        whoSpentInput = findViewById(R.id.who_spent_input);
        amountInput = findViewById(R.id.amount_input);
        saveButton = findViewById(R.id.save_button);
        cancelButton = findViewById(R.id.cancel_button);

        // Initialize database helper
        dbHelper = new ExpenseDatabaseHelper(this);

        // Set up button click listeners
        saveButton.setOnClickListener(v -> saveExpense());
        cancelButton.setOnClickListener(v -> finish());
    }

    private void saveExpense() {
        String purpose = purposeInput.getText().toString().trim();
        String name = whoSpentInput.getText().toString().trim();
        String amountStr = amountInput.getText().toString().trim();

        // Validate inputs
        if (purpose.isEmpty() || name.isEmpty() || amountStr.isEmpty()) {
            Toast.makeText(this, "Please fill all fields", Toast.LENGTH_SHORT).show();
            return;
        }

        try {
            int amount = Integer.parseInt(amountStr);

            // Create a new expense object (id will be auto-generated by the database)
            Expense expense = new Expense(0, name, purpose, amount);

            // Save to database
            dbHelper.insertExpense(expense);

            Toast.makeText(this, "Expense saved successfully", Toast.LENGTH_SHORT).show();

            // Close the activity and return to previous screen
            finish();
        } catch (NumberFormatException e) {
            Toast.makeText(this, "Please enter a valid amount", Toast.LENGTH_SHORT).show();
        }
    }
}